config/routes.rb
Rails.application.routes.draw do

  root 'home#form'
  get 'home/form'
  post 'home/form'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def form
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/form.html.erb
<% if request.post? %> 
  Thanks for submitting the form!  Here are your answers:<br>
  Name: <%= params[:name] %><br>
  Do you like Chocolate? <%= params[:chocolate] ? "Yes!" : "No" %><br>
  Do you like Rainbows? <%= params[:rainbows] ? "Yes!" : "No" %><br>
  Do you like Puppies? <%= params[:puppies] ? "Yes!" : "No" %><br>
  Do you like Cold Hard Cash? <%= params[:cash] ? "Yes!" : "No" %><br>
<% else %>
  <%= form_tag home_form_path do %>
    <div>
      Name: <%= text_field_tag :name %>
    </div>
    <div>
      Favorites:
      <ul>
        <li class="item">
          <%= check_box_tag :chocolate %> I like <%= label_tag :chocolate %>
        </li>
        <li class="item">
          <%= check_box_tag :rainbows %> I like <%= label_tag :rainbows %>
        </li>
        <li class="item">
          <%= check_box_tag :puppies %> I like <%= label_tag :puppies %>
        </li>
        <li class="item">
          <%= check_box_tag :cold_hard_cash %> I like <%= label_tag :cold_hard_cash %>
        </li>
      </ul>
    </div>
    <%= submit_tag %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChallenges</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>